StockMarket/src/objects/DailyData__c.object
<CustomObject>
    <description>日线数据</description>
    <fields>
        <fullName>AvgPrice__c</fullName>
        <description>日均价</description>
        <label>AvgPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Close_Price__c</fullName>
        <description>昨日收盘价</description>
        <label>Close Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <description>当前价，今日收盘价</description>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT__c</fullName>
        <description>日期</description>
        <label>DT</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>High_Price__c</fullName>
        <description>最高价</description>
        <label>High Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Price__c</fullName>
        <description>最低价</description>
        <label>Low Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Price__c</fullName>
        <description>开盘价</description>
        <label>Open Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <description>成交量</description>
        <label>Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>DailyData</relationshipLabel>
        <relationshipName>DailyData</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>成交量</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DailyData</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>DailyData名称</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <fields>
        <fullName>Stock_Code__c</fullName>
        <description>股票编码</description>
        <label>Stock Code</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Stock_Exchange__c</fullName>
        <description>交易所代码</description>
        <label>Stock Exchange</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>sh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>sz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_Market_Index__c</fullName>
        <defaultValue>false</defaultValue>
        <description>是否股指，默认为否</description>
        <label>Stock Market Index</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isGrab__c</fullName>
        <defaultValue>true</defaultValue>
        <description>是否抓取</description>
        <label>isGrab</label>
        <type>Checkbox</type>
    </fields>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/StockDailyDataDao.cls
/**
 * DailyData 对象CRUD操作类
 */
public with sharing class StockDailyDataDao extends BaseDao {

	public StockDailyDataDao(){
        this.sosql_all = 'SELECT Id,Name,'
                +'Close_Price__c, Current_Price__c, DT__c, High_Price__c,'
                +'Low_Price__c, Open_Price__c,AvgPrice__c,Quota__c,Volume__c,'
                +'Stock__c,Stock__r.Name,Stock__r.Stock_Code__c,Stock__r.Stock_Exchange__c,'
                +'Stock__r.Stock_Market_Index__c,Stock__r.isGrab__c '
                +'FROM DailyData__c ';
    }

    /**
     [getDailyDataByStockId 根据股票id列表,查询日线数据]
     * @param  []stockIds [description]
     * @return            [description]
     */
    public List<DailyData__c> getDailyDataByStockIds(String []stockIds){
    	if(stockIds == null) return null;

        if(stockIds.isEmpty()) return null;
        
        String queryStr = sosql_all +' WHERE Stock__c IN:stockIds order by DT__c DESC';

        List<DailyData__c> stockList = Database.query(queryStr);

        return stockList;
    }

    /**
     [getDailyDataByStockId 根据股票id,查询日线数据]
     * @param  stockId [description]
     * @return         [description]
     */
    public List<DailyData__c> getDailyDataByStockId(String stockId){
    	if(String.isBlank(stockId)) return null;
        return getDailyDataByStockIds(new String[]{stockId});
    }

    /**
     [update 更新日线数据]
     * @param  dailyDatas [description]
     * @return            [description]
     */
    public List<String> updateDailyData(List<DailyData__c> dailyDatas) {
        return super.save(dailyDatas, false);
    }

    /**
     [insert 插入日线数据]
     * @param  dailyDatas [description]
     * @return            [description]
     */
    public List<String> insertDailyData(List<DailyData__c> dailyDatas) {
        return super.save(dailyDatas, true);
    }
    
}