StockMarket/src/objects/DailyData__c.object
<CustomObject>
    <description>日线数据</description>
    <fields>
        <fullName>AvgPrice__c</fullName>
        <description>日均价</description>
        <label>AvgPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Close_Price__c</fullName>
        <description>昨日收盘价</description>
        <label>Close Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <description>当前价，今日收盘价</description>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT__c</fullName>
        <description>日期</description>
        <label>DT</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>High_Price__c</fullName>
        <description>最高价</description>
        <label>High Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Price__c</fullName>
        <description>最低价</description>
        <label>Low Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Price__c</fullName>
        <description>开盘价</description>
        <label>Open Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <description>成交量</description>
        <label>Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>DailyData</relationshipLabel>
        <relationshipName>DailyData</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>成交量</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DailyData</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>DailyData名称</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <fields>
        <fullName>isGrab__c</fullName>
        <defaultValue>true</defaultValue>
        <description>是否抓取</description>
        <label>isGrab</label>
        <type>Checkbox</type>
    </fields>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock_RTInfo__c.object
<CustomObject>
    <description>用于保存股票某周期内的报价</description>
    <fields>
        <fullName>Close_Price__c</fullName>
        <description>昨日收盘价</description>
        <label>Close Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <description>当前价</description>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT__c</fullName>
        <description>发生时间</description>
        <label>DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>High_Price__c</fullName>
        <description>今日最高价</description>
        <label>High Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Price__c</fullName>
        <description>今日最低价</description>
        <label>Low Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Price__c</fullName>
        <description>今日开盘价</description>
        <label>Open Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <description>成交额</description>
        <label>Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StockName__c</fullName>
        <description>股票名称</description>
        <label>StockName</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>Stock RTInfo</relationshipLabel>
        <relationshipName>Stock_RTInfo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>成交量</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Stock RTInfo</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000000}</displayFormat>
        <label>股票实时信息</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/DailyDataAggregateSchedular.cls
/**
 *
    每天定时将实时数据聚合到日线数据上
    DailyDataAggregateSchedular gs = new DailyDataAggregateSchedular();
    String sch1 = '0 10 15 ? * MON-FRI';
    system.schedule('DailyDataAggregateSchedular', sch1, gs);
 */
global class DailyDataAggregateSchedular implements Schedulable {

    global void execute(SchedulableContext sc) {
        //日开盘、收盘、最高、最低、均价价格，日成交额，日成交量
        StockRTInfoDao srtDao = new StockRTInfoDao();
        //查询实时股票的最后一次抓取数据
        List<Stock_RTInfo__c> srtInfos 
        	= srtDao.getStockRTInfoByCondition('WHERE DT__c = TODAY AND HOUR_IN_DAY(DT__c) = 7');
    	
      	Map<String,Stock_RTInfo__c> id_rt_map = new Map<String,Stock_RTInfo__c>();
      	for(Stock_RTInfo__c rt:srtInfos){
      		  id_rt_map.put(rt.Stock__c, rt);
      	}
    	
    	  StockDao sd = new StockDao();
        List<Stock__c> stockList = sd.getStockByCondition('WHERE isGrab__c=true');

        //设置均价
        AggregateResult[] groupedResults = [
            SELECT 
              Stock__c,
              Avg(Current_Price__c)
      			FROM 
              Stock_RTInfo__c 
      			WHERE DT__c = TODAY
      			GROUP BY StockName__c,Stock__c,DAY_ONLY(DT__c)
        ];

      	Map<String,Decimal> stockId_avgMap = new Map<String,Decimal>();

    		for (AggregateResult ar : groupedResults) {
    			 stockId_avgMap.put((String)ar.get('Stock__c'), (Decimal)ar.get('expr0'));
    		}

        List<DailyData__c> dds = new List<DailyData__c>();

        for(Stock__c stk:stockList){
            Stock_RTInfo__c rt = id_rt_map.get(stk.Id);
            DailyData__c ddc = new DailyData__c();

            ddc.Stock__c = stk.Id;
            ddc.Open_Price__c = rt.Open_Price__c;
            ddc.Close_Price__c = rt.Close_Price__c;
            ddc.High_Price__c = rt.High_Price__c;
            ddc.Low_Price__c = rt.Low_Price__c;
            ddc.Volume__c 	= rt.Volume__c;
            ddc.Quota__c = rt.Quota__c;
            ddc.Current_Price__c = rt.Current_Price__c;
            if(!stockId_avgMap.isEmpty())
            		ddc.AvgPrice__c = stockId_avgMap.get(stk.Id);
            ddc.DT__c = rt.DT__c.date();
            dds.add(ddc);
        }

        StockDailyDataDao dailyDataDao = new StockDailyDataDao();
        List<String> savedIds = dailyDataDao.insertDailyData(dds);
        System.debug('Saved Ids are '+savedIds);
    }
}