StockMarket/src/objects/DailyData__c.object
<CustomObject>
    <description>日线数据</description>
    <fields>
        <fullName>AvgPrice__c</fullName>
        <description>日均价</description>
        <label>AvgPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Close_Price__c</fullName>
        <description>昨日收盘价</description>
        <label>Close Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <description>当前价，今日收盘价</description>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT__c</fullName>
        <description>日期</description>
        <label>DT</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>High_Price__c</fullName>
        <description>最高价</description>
        <label>High Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Price__c</fullName>
        <description>最低价</description>
        <label>Low Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Price__c</fullName>
        <description>开盘价</description>
        <label>Open Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <description>成交量</description>
        <label>Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>DailyData</relationshipLabel>
        <relationshipName>DailyData</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>成交量</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DailyData</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>DailyData名称</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <fields>
        <fullName>Stock_Code__c</fullName>
        <description>股票编码</description>
        <label>Stock Code</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Stock_Exchange__c</fullName>
        <description>交易所代码</description>
        <label>Stock Exchange</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>sh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>sz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_Market_Index__c</fullName>
        <defaultValue>false</defaultValue>
        <description>是否股指，默认为否</description>
        <label>Stock Market Index</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isGrab__c</fullName>
        <defaultValue>true</defaultValue>
        <description>是否抓取</description>
        <label>isGrab</label>
        <type>Checkbox</type>
    </fields>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/StockDailyDataDaoTest.cls
@isTest
private class StockDailyDataDaoTest {

	@testSetup
	static void setup(){
		List<Stock__c> slist = new List<Stock__c>();

		Stock__c stock = new Stock__c(
			Name='北方导航',
			Stock_Code__c='600435',
			isGrab__c=true,
			Stock_Exchange__c='sh',
			Stock_Market_Index__c=false);
		slist.add(stock);

		stock = new Stock__c(
			Name='上证指数',
			Stock_Code__c='000001',
			isGrab__c=true,
			Stock_Exchange__c='sh',
			Stock_Market_Index__c=true);
		slist.add(stock);

		insert slist;
	}


    static testMethod void testAllGet() {
    	StockDao sdao = new StockDao();
    	Stock__c stock = sdao.getStockByCode('600435');
    	System.assert(true, stock!=null);
        StockDailyDataDao sddao = new StockDailyDataDao();
    	System.assertEquals(null, sddao.getDailyDataByStockId(null));
    	System.assertEquals(0, sddao.getDailyDataByStockId(stock.Id).size());
    	System.assertEquals(null, sddao.getDailyDataByStockIds(null));
    	System.assertEquals(null, sddao.getDailyDataByStockIds(new String[]{}));
    	System.assertEquals(0, sddao.getDailyDataByStockIds(new String[]{stock.Id}).size());
    }

    @isTest
    static void testSave() {
    	StockDao sdao = new StockDao();
    	Stock__c stock = sdao.getStockByCode('600435');
    	List<DailyData__c> dds = new List<DailyData__c>();

    	//插入新数据
        for(Integer i=0;i<10;i++){
        	DailyData__c ddc = new DailyData__c();

        	ddc.Stock__c = stock.Id;
        	ddc.Open_Price__c = Math.random()+15;
	        ddc.Close_Price__c = Math.random()+15;
	        ddc.High_Price__c = Math.random()+15;
	        ddc.Low_Price__c = Math.random()+15;
	        ddc.Volume__c 	= Math.random()*20000;
	        ddc.Quota__c = Math.random()*20000;
	        ddc.Current_Price__c = Math.random()+15;
	        ddc.AvgPrice__c = Math.random()+15;
	        ddc.DT__c = DateTime.now().date();

	        dds.add(ddc);
        }

        StockDailyDataDao sddao = new StockDailyDataDao();

        List<String> sl = sddao.insertDailyData(dds);
        System.assertEquals(10, sl.size());

        //获取刚插入的数据
        System.assertEquals(10, sddao.getDailyDataByStockId(stock.Id).size());
        System.assertEquals(10, sddao.getDailyDataByStockIds(new String[]{stock.Id}).size());

        //更新操作
        dds = sddao.getDailyDataByStockId(stock.Id);
        System.assert(true, dds!=null);
        for(DailyData__c dd:dds){
        	dd.AvgPrice__c = Math.random()+18;
        }
        sl = sddao.updateDailyData(dds);
        System.assertEquals(10, sl.size());

        //Error
        sl = sddao.insertDailyData(dds);
        System.assertEquals(0, sl.size());

        System.assertEquals(null, sddao.updateDailyData(null));
        System.assertEquals(null, sddao.updateDailyData(new List<DailyData__c>()));

    }
}