StockMarket/src/objects/GrabURL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>抓取Url</description>
    <fields>
        <fullName>GrabUrl__c</fullName>
        <description>抓取url</description>
        <label>GrabUrl</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>GrabURL</label>
</CustomObject>

StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <fields>
        <fullName>Stock_Full_Name__c</fullName>
        <formula>TEXT(Stock_Exchange__c) &amp;   Stock_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stock Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isGrab__c</fullName>
        <defaultValue>true</defaultValue>
        <description>是否抓取</description>
        <label>isGrab</label>
        <type>Checkbox</type>
    </fields>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock_RTInfo__c.object
<CustomObject>
    <description>用于保存股票某周期内的报价</description>
    <fields>
        <fullName>Buy1_Price__c</fullName>
        <label>Buy1_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy1_Volume__c</fullName>
        <description>买一量</description>
        <label>Buy1_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy2_Price__c</fullName>
        <label>Buy2_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy2_Volume__c</fullName>
        <description>买二量</description>
        <label>Buy2_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy3_Price__c</fullName>
        <label>Buy3_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy3_Volume__c</fullName>
        <label>Buy3_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy4_Price__c</fullName>
        <label>Buy4_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy4_Volume__c</fullName>
        <label>Buy4_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy5_Price__c</fullName>
        <label>Buy5_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy5_Volume__c</fullName>
        <label>Buy5_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy_Price__c</fullName>
        <description>竞买价</description>
        <label>Buy Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Close_Price__c</fullName>
        <description>昨日收盘价</description>
        <label>Close Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <description>当前价</description>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT__c</fullName>
        <description>发生时间</description>
        <label>DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>High_Price__c</fullName>
        <description>今日最高价</description>
        <label>High Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Price__c</fullName>
        <description>今日最低价</description>
        <label>Low Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Price__c</fullName>
        <description>今日开盘价</description>
        <label>Open Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <description>成交额</description>
        <label>Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell1_Price__c</fullName>
        <label>Sell1_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell1_Volume__c</fullName>
        <description>卖1量</description>
        <label>Sell1_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell2_Price__c</fullName>
        <label>Sell2_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell2_Volume__c</fullName>
        <label>Sell2_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell3_Price__c</fullName>
        <label>Sell3_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell3_Volume__c</fullName>
        <label>Sell3_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell4_Price__c</fullName>
        <label>Sell4_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell4_Volume__c</fullName>
        <label>Sell4_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell5_Price__c</fullName>
        <label>Sell5_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell5_Volume__c</fullName>
        <label>Sell5_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell_Price__c</fullName>
        <description>竞卖价</description>
        <label>Sell Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StockName__c</fullName>
        <description>股票名称</description>
        <label>StockName</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>Stock RTInfo</relationshipLabel>
        <relationshipName>Stock_RTInfo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>成交量</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Stock RTInfo</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000000}</displayFormat>
        <label>股票实时信息</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/StockSpider.cls
/**
 * 抓取股票信息类
 * 将Stock表的股票全部读出，向指定网站发出请求，
 * 获取数据插入到StockRTInfo表
 */
public without sharing class StockSpider {

    public String web {set;get;}

    public String grabUrl{set;get;}

    public StockSpider(){
        this.web = 'Sina';
        this.grabUrl = GrabURL__c.getAll().get(this.web).GrabUrl__c;
    }

    public void doAction(){
        StockDao sd = new StockDao();
        List<Stock__c> stockList = sd.getAllStockList();

        String params = '';
        for(Stock__c stk:stockList){
            if(stk.isGrab__c){
                params+= stk.Stock_Full_Name__c+',';
            }
        }

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(this.grabUrl+'/list='+params);
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            String resString = response.getBody();
            System.debug(resString);
            saveDataToDb(resString);
        }else{
            System.debug(response.getStatusCode());
        }
    }

    /**
     [saveDataToDb 保存数据到数据库]
     * @param  resString [description]
     * @return           [description]
     */
    public List<Stock_RTInfo__c> saveDataToDb(String resString){
        String []lines = resString.split('\n');
        System.debug(lines.size());

        List<Stock_RTInfo__c> srtlist = new List<Stock_RTInfo__c>();
        for(String line:lines){
            String line_clean = line.substringBetween('"');
            System.debug(line_clean);
            String [] f = line_clean.split(',');
            Stock_RTInfo__c src = new Stock_RTInfo__c();
            src.Buy1_Price__c = Decimal.valueOf(f[11]);
            src.Buy1_Volume__c = Decimal.valueOf(f[10]);
            src.Buy2_Price__c = Decimal.valueOf(f[13]);
            src.Buy2_Volume__c = Decimal.valueOf(f[12]);
            src.Buy3_Price__c = Decimal.valueOf(f[15]);
            src.Buy3_Volume__c = Decimal.valueOf(f[14]);
            src.Buy4_Price__c = Decimal.valueOf(f[17]);
            src.Buy4_Volume__c = Decimal.valueOf(f[16]);
            src.Buy5_Price__c = Decimal.valueOf(f[19]);
            src.Buy5_Volume__c = Decimal.valueOf(f[18]);
            src.Buy_Price__c = Decimal.valueOf(f[6]);
            src.Close_Price__c = Decimal.valueOf(f[2]);
            src.Current_Price__c = Decimal.valueOf(f[3]);
            src.DT__c = Datetime.valueOf(f[30]+' '+f[31]);
            src.High_Price__c = Decimal.valueOf(f[4]);
            src.Low_Price__c = Decimal.valueOf(f[5]);
            src.Open_Price__c = Decimal.valueOf(f[1]);
            src.Quota__c = Decimal.valueOf(f[9]);
            src.Sell1_Price__c = Decimal.valueOf(f[21]);
            src.Sell1_Volume__c = Decimal.valueOf(f[20]);
            src.Sell2_Price__c = Decimal.valueOf(f[23]);
            src.Sell2_Volume__c = Decimal.valueOf(f[22]);
            src.Sell3_Price__c = Decimal.valueOf(f[25]);
            src.Sell3_Volume__c = Decimal.valueOf(f[24]);
            src.Sell4_Price__c = Decimal.valueOf(f[27]);
            src.Sell4_Volume__c = Decimal.valueOf(f[26]);
            src.Sell5_Price__c = Decimal.valueOf(f[29]);
            src.Sell5_Volume__c = Decimal.valueOf(f[28]);
            src.Sell_Price__c = Decimal.valueOf(f[7]);
            // src.Stock__c = f[0]; //交给trigger去设置
            src.StockName__c = f[0];
            src.Volume__c = Decimal.valueOf(f[8]);
            srtlist.add(src);
        }
        if(srtlist.size()>0){
            insert srtlist;
        }
        return srtlist;
    }
}