StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <fields>
        <fullName>Stock_Code__c</fullName>
        <description>股票编码</description>
        <label>Stock Code</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Stock_Exchange__c</fullName>
        <description>交易所代码</description>
        <label>Stock Exchange</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>sh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>sz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_Market_Index__c</fullName>
        <defaultValue>false</defaultValue>
        <description>是否股指，默认为否</description>
        <label>Stock Market Index</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isGrab__c</fullName>
        <defaultValue>true</defaultValue>
        <description>是否抓取</description>
        <label>isGrab</label>
        <type>Checkbox</type>
    </fields>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock_RTInfo__c.object
<CustomObject>
    <description>用于保存股票某周期内的报价</description>
    <fields>
        <fullName>Buy1_Price__c</fullName>
        <label>Buy1_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy1_Volume__c</fullName>
        <description>买一量</description>
        <label>Buy1_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy2_Price__c</fullName>
        <label>Buy2_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy2_Volume__c</fullName>
        <description>买二量</description>
        <label>Buy2_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy3_Price__c</fullName>
        <label>Buy3_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy3_Volume__c</fullName>
        <label>Buy3_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy4_Price__c</fullName>
        <label>Buy4_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy4_Volume__c</fullName>
        <label>Buy4_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy5_Price__c</fullName>
        <label>Buy5_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy5_Volume__c</fullName>
        <label>Buy5_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy_Price__c</fullName>
        <description>竞买价</description>
        <label>Buy Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Close_Price__c</fullName>
        <description>昨日收盘价</description>
        <label>Close Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <description>当前价</description>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT__c</fullName>
        <description>发生时间</description>
        <label>DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>High_Price__c</fullName>
        <description>今日最高价</description>
        <label>High Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LongOrShort__c</fullName>
        <description>看多，看空，看平</description>
        <label>LongOrShort</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>多</fullName>
                </value>
                <value>
                    <fullName>平</fullName>
                </value>
                <value>
                    <fullName>空</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Low_Price__c</fullName>
        <description>今日最低价</description>
        <label>Low Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Price__c</fullName>
        <description>今日开盘价</description>
        <label>Open Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <description>成交额</description>
        <label>Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell1_Price__c</fullName>
        <label>Sell1_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell1_Volume__c</fullName>
        <description>卖1量</description>
        <label>Sell1_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell2_Price__c</fullName>
        <label>Sell2_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell2_Volume__c</fullName>
        <label>Sell2_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell3_Price__c</fullName>
        <label>Sell3_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell3_Volume__c</fullName>
        <label>Sell3_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell4_Price__c</fullName>
        <label>Sell4_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell4_Volume__c</fullName>
        <label>Sell4_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell5_Price__c</fullName>
        <label>Sell5_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell5_Volume__c</fullName>
        <label>Sell5_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell_Price__c</fullName>
        <description>竞卖价</description>
        <label>Sell Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StockName__c</fullName>
        <description>股票名称</description>
        <label>StockName</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>Stock RTInfo</relationshipLabel>
        <relationshipName>Stock_RTInfo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>成交量</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Stock RTInfo</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000000}</displayFormat>
        <label>股票实时信息</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/StockRTInfoDaoTest.cls
@isTest
private class StockRTInfoDaoTest {

	@testSetup
	static void setup(){

		List<Stock__c> slist = new List<Stock__c>();

		Stock__c stock = new Stock__c(
			Name='北方导航',
			Stock_Code__c='600435',
			isGrab__c=true,
			Stock_Exchange__c='sh',
			Stock_Market_Index__c=false);
		slist.add(stock);

		stock = new Stock__c(
			Name='上证指数',
			Stock_Code__c='000001',
			isGrab__c=true,
			Stock_Exchange__c='sh',
			Stock_Market_Index__c=true);
		slist.add(stock);

		insert slist;

		List<Stock_RTInfo__c> srtList = new List<Stock_RTInfo__c>();
		for(Integer i=0; i<10; i++){
			Stock_RTInfo__c src = new Stock_RTInfo__c();
			// src.LongOrShort__c = '平';
			src.Buy1_Price__c = Math.random()+15;
	        src.Buy1_Volume__c = Math.random()*1000;
	        src.Buy2_Price__c = Math.random()+15;
	        src.Buy2_Volume__c = Math.random()*1000;
	        src.Buy3_Price__c = Math.random()+15;
	        src.Buy3_Volume__c = Math.random()*1000;
	        src.Buy4_Price__c = Math.random()+15;
	        src.Buy4_Volume__c = Math.random()*1000;
	        src.Buy5_Price__c = Math.random()+15;
	        src.Buy5_Volume__c = Math.random()*1000;
	        src.Buy_Price__c = Math.random()+15;
	        src.Close_Price__c = Math.random()+15;
	        src.Current_Price__c = Math.random()+15;
	        src.DT__c = Datetime.now();
	        src.High_Price__c = Math.random()+16;
	        src.Low_Price__c = Math.random()+15;
	        src.Open_Price__c = Math.random()+15;
	        src.Quota__c = 2300458;
	        src.Sell1_Price__c = Math.random()+15;
	        src.Sell1_Volume__c = Math.random()*1000;
	        src.Sell2_Price__c = Math.random()+15;
	        src.Sell2_Volume__c = Math.random()*1000;
	        src.Sell3_Price__c = Math.random()+15;
	        src.Sell3_Volume__c = Math.random()*1000;
	        src.Sell4_Price__c = Math.random()+15;
	        src.Sell4_Volume__c = Math.random()*1000;
	        src.Sell5_Price__c = Math.random()+15;
	        src.Sell5_Volume__c = Math.random()*1000;
	        src.Sell_Price__c = Math.random()+15;
	        // src.Stock__c = f[0]; //交给trigger去设置
	        src.StockName__c = '北方导航';
	        src.Volume__c = Math.random()*1000909;
	        srtList.add(src);
	    }
        insert srtList;
	}

    static testMethod void testAllGet() {
        StockRTInfoDao srtDao = new StockRTInfoDao();
        System.assertEquals(null, srtDao.getStockRTInfoByCondition(''));
        System.assertEquals(10, srtDao.getStockRTInfoByCondition('Where StockName__c=\'北方导航\'').size());
        System.assertEquals(10, srtDao.getMonthlyStockRTInfo().size());

        StockDao sDao = new StockDao();
        Stock__c stock = sDao.getStockByName('北方导航');
        System.assertEquals(null, srtDao.getTodayStockRTInfoByStockId(null));
        System.assertEquals(10, srtDao.getTodayStockRTInfoByStockId(stock.Id).size());
        System.assertEquals(null, srtDao.getTodayStockRTInfoByStockIds(null));
        System.assertEquals(null, srtDao.getTodayStockRTInfoByStockIds(new String[]{}));
        System.assertEquals(10, srtDao.getTodayStockRTInfoByStockIds(new String[]{stock.Id}).size());
    }

    @isTest
    static void testRemove(){
    	StockRTInfoDao srtDao = new StockRTInfoDao();
    	System.assertEquals(null, srtDao.remove(null));
    	System.assertEquals(null, srtDao.remove(new List<Stock_RTInfo__c>()));
    	System.assertEquals(10, srtDao.remove(srtDao.getMonthlyStockRTInfo()).size());
    }
}