StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <fields>
        <fullName>Stock_Market_Index__c</fullName>
        <defaultValue>false</defaultValue>
        <description>是否股指，默认为否</description>
        <label>Stock Market Index</label>
        <type>Checkbox</type>
    </fields>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock_RTInfo__c.object
<CustomObject>
    <description>用于保存股票某周期内的报价</description>
    <fields>
        <fullName>Buy1_Volume__c</fullName>
        <description>买一量</description>
        <label>Buy1_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy2_Volume__c</fullName>
        <description>买二量</description>
        <label>Buy2_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy3_Volume__c</fullName>
        <label>Buy3_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy4_Volume__c</fullName>
        <label>Buy4_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy5_Volume__c</fullName>
        <label>Buy5_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT__c</fullName>
        <description>发生时间</description>
        <label>DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LongOrShort__c</fullName>
        <description>看多，看空，看平</description>
        <label>LongOrShort</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>多</fullName>
                </value>
                <value>
                    <fullName>平</fullName>
                </value>
                <value>
                    <fullName>空</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sell1_Volume__c</fullName>
        <description>卖1量</description>
        <label>Sell1_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell2_Volume__c</fullName>
        <label>Sell2_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell3_Volume__c</fullName>
        <label>Sell3_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell4_Volume__c</fullName>
        <label>Sell4_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell5_Volume__c</fullName>
        <label>Sell5_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>Stock RTInfo</relationshipLabel>
        <relationshipName>Stock_RTInfo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Stock RTInfo</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000000}</displayFormat>
        <label>股票实时信息</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/ComputeLongOrShortBatchable.cls
global class ComputeLongOrShortBatchable implements Database.Batchable<sObject>,Database.Stateful {
    
    public String query;

    global Integer count = 0;//总记录数

    global Integer longCount=0;//看多个数
    global Integer shortCount=0;//看空个数
    global Integer equalCount=0;//看平个数

    global ComputeLongOrShortBatchable() {
        this.query = 'SELECT Id,Name,Buy1_Volume__c,Buy2_Volume__c,Buy3_Volume__c,'
                    + 'Buy4_Volume__c,Buy5_Volume__c,Sell1_Volume__c,Sell2_Volume__c,'
                    + 'Sell3_Volume__c,Sell4_Volume__c,Sell5_Volume__c,LongOrShort__c,'
                    + 'Stock__r.Stock_Market_Index__c '
                    + 'From Stock_RTInfo__c WHERE DT__c = LAST_MONTH ' //TODAY
                    + 'AND Stock__r.Stock_Market_Index__c=false';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        StockRTInfoDao srtDao = new StockRTInfoDao();
        List<Stock_RTInfo__c> rtlist = (List<Stock_RTInfo__c>) scope;
        for(Stock_RTInfo__c srt:rtlist){

            // srt.LongOrShort__c = null;

            Double buy = srt.Buy1_Volume__c
                        +srt.Buy2_Volume__c
                        +srt.Buy3_Volume__c
                        +srt.Buy4_Volume__c
                        +srt.Buy5_Volume__c;

            Double sell = srt.Sell1_Volume__c
                        +srt.Sell2_Volume__c
                        +srt.Sell3_Volume__c
                        +srt.Sell4_Volume__c
                        +srt.Sell5_Volume__c;

            Double absValue = Math.abs(buy-sell); //多空数相减绝对值

            if(absValue/(buy+sell) <= 0.05){ //绝对值占比多空总数的5%以内为看平
                srt.LongOrShort__c = '平';
                equalCount++;
            }else{
                if(buy > sell){
                    srt.LongOrShort__c = '多';
                    longCount++;
                }else{
                    srt.LongOrShort__c = '空';
                    shortCount++;
                }
            }

        }
        List<String> updatedId = srtDao.save(rtlist, false);
        count += updatedId.size();
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Computed total '+count+' records!');
        AsyncApexJob a = [
            SELECT 
                Id, 
                Status, 
                NumberOfErrors, 
                JobItemsProcessed,
                TotalJobItems, 
                CreatedBy.Email
            FROM 
                AsyncApexJob 
            WHERE Id = :BC.getJobId()];

        //发送邮件给创建者
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {a.CreatedBy.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('今天多空对决计算结果状态 ' + a.Status+ '，共计算：'+count +' 条记录');

        mail.setPlainTextBody(
            '今天多空对决计算任务总批量：' 
            + a.TotalJobItems 
            + '，总记录数：'+count
            +'，出错记录数：'
            + a.NumberOfErrors + ' 条；'
            +'看多记录：'+longCount
            +'，看空记录：'+shortCount
            +'，看平记录：'+equalCount+'。'
            );
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    }
}