StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock_RTInfo__c.object
<CustomObject>
    <description>用于保存股票某周期内的报价</description>
    <fields>
        <fullName>StockName__c</fullName>
        <description>股票名称</description>
        <label>StockName</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>Stock RTInfo</relationshipLabel>
        <relationshipName>Stock_RTInfo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Stock RTInfo</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000000}</displayFormat>
        <label>股票实时信息</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/StockRTInfoSetStockIdHandler.cls
/**
 * 插入实时股票信息时，关联上股票信息
 */
public without sharing class StockRTInfoSetStockIdHandler implements Triggers.Handler {

	public void handle() {

		Set<String> nameset = new Set<String>();
		for(Stock_RTInfo__c item:(List<Stock_RTInfo__c>)Trigger.new){
            nameset.add(item.StockName__c);
        }

        StockDao sd = new StockDao();
        String []names = new List<String>(nameset);
        
        //根据股票名称查出所有的Stock信息。
        List<Stock__c> stockList = sd.getStockListByNames(names);
        Map<String,String> name_id_map = new Map<String,String>();
        for(Stock__c sto:stockList){
        	name_id_map.put(sto.Name, sto.Id);
        }

        for(Stock_RTInfo__c st:(List<Stock_RTInfo__c>)Trigger.new){
	        if(st.Stock__c == null){
	        	st.Stock__c = name_id_map.get(st.StockName__c);
	        }
	    }
	}
    
}