StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/objects/Stock_RTInfo__c.object
<CustomObject>
    <description>用于保存股票某周期内的报价</description>
    <fields>
        <fullName>Buy1_Price__c</fullName>
        <label>Buy1_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy1_Volume__c</fullName>
        <description>买一量</description>
        <label>Buy1_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy2_Price__c</fullName>
        <label>Buy2_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy2_Volume__c</fullName>
        <description>买二量</description>
        <label>Buy2_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy3_Price__c</fullName>
        <label>Buy3_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy3_Volume__c</fullName>
        <label>Buy3_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy4_Price__c</fullName>
        <label>Buy4_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy4_Volume__c</fullName>
        <label>Buy4_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy5_Price__c</fullName>
        <label>Buy5_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy5_Volume__c</fullName>
        <label>Buy5_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buy_Price__c</fullName>
        <description>竞买价</description>
        <label>Buy Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Close_Price__c</fullName>
        <description>昨日收盘价</description>
        <label>Close Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <description>当前价</description>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT__c</fullName>
        <description>发生时间</description>
        <label>DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>High_Price__c</fullName>
        <description>今日最高价</description>
        <label>High Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LongOrShort__c</fullName>
        <description>看多，看空，看平</description>
        <label>LongOrShort</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>多</fullName>
                </value>
                <value>
                    <fullName>平</fullName>
                </value>
                <value>
                    <fullName>空</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Low_Price__c</fullName>
        <description>今日最低价</description>
        <label>Low Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Price__c</fullName>
        <description>今日开盘价</description>
        <label>Open Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quota__c</fullName>
        <description>成交额</description>
        <label>Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell1_Price__c</fullName>
        <label>Sell1_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell1_Volume__c</fullName>
        <description>卖1量</description>
        <label>Sell1_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell2_Price__c</fullName>
        <label>Sell2_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell2_Volume__c</fullName>
        <label>Sell2_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell3_Price__c</fullName>
        <label>Sell3_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell3_Volume__c</fullName>
        <label>Sell3_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell4_Price__c</fullName>
        <label>Sell4_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell4_Volume__c</fullName>
        <label>Sell4_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell5_Price__c</fullName>
        <label>Sell5_Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell5_Volume__c</fullName>
        <label>Sell5_Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sell_Price__c</fullName>
        <description>竞卖价</description>
        <label>Sell Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StockName__c</fullName>
        <description>股票名称</description>
        <label>StockName</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>股票信息</description>
        <label>Stock</label>
        <referenceTo>Stock__c</referenceTo>
        <relationshipLabel>Stock RTInfo</relationshipLabel>
        <relationshipName>Stock_RTInfo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>成交量</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Stock RTInfo</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000000}</displayFormat>
        <label>股票实时信息</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/StockRTInfoDao.cls
/**
 * Stock_RTInfo__c 对象CRUD操作类
 */
public without sharing class StockRTInfoDao extends BaseDao{

    private String sosql_all = 'SELECT Id,Name,LongOrShort__c,Buy1_Price__c, Buy1_Volume__c, Buy2_Price__c, Buy2_Volume__c, '
                    +'Buy3_Price__c, Buy3_Volume__c, Buy4_Price__c, Buy4_Volume__c, Buy5_Price__c, '
                    +'Buy5_Volume__c, Buy_Price__c, Close_Price__c, Current_Price__c, DT__c, High_Price__c, '
                    +'Low_Price__c, Open_Price__c, Quota__c, Sell1_Price__c, Sell1_Volume__c, Sell2_Price__c, '
                    +'Sell2_Volume__c, Sell3_Price__c, Sell3_Volume__c, Sell4_Price__c, Sell4_Volume__c, '
                    +'Sell5_Price__c, Sell5_Volume__c, Sell_Price__c, Stock__c, StockName__c, Volume__c '
                    +'FROM Stock_RTInfo__c ';

    /**
     [getStockRTInfoByCondition 自定义条件查询实时股票列表]
     * @param  condition [description]
     * @return           [description]
     */
    public List<Stock_RTInfo__c> getStockRTInfoByCondition(String condition){
        if(String.isBlank(condition)){
            return null;
        }

        String queryStr = sosql_all +' '+condition;

        List<Stock_RTInfo__c> stockList = Database.query(queryStr);

        return stockList;
    }
    
    /**
     * [getStockRTInfoByStockIds 根据股票Id列表查询实时信息列表]
     * @param  []stockIds [description]
     * @return            [description]
     */
    public List<Stock_RTInfo__c> getTodayStockRTInfoByStockIds(String []stockIds){
        if(stockIds == null) return null;

        if(stockIds.isEmpty()) return null;

        String queryStr = sosql_all +' WHERE Stock__c IN:stockIds and DT__c = TODAY order by DT__c DESC';

        List<Stock_RTInfo__c> stockList = Database.query(queryStr);

        return stockList;
    }

    /**
     * [getMonthlyStockRTInfo 获取当月所有数据]
     * @return [description]
     */
    public List<Stock_RTInfo__c> getMonthlyStockRTInfo(){
        
        String queryStr = sosql_all +' WHERE DT__c = THIS_MONTH';

        List<Stock_RTInfo__c> stockList = Database.query(queryStr);

        return stockList;
    }

    /**
     [getStockRTInfoByStockId 根据股票Id查询实时信息列表]
     * @param  stockId [description]
     * @return            [description]
     */
    public List<Stock_RTInfo__c> getTodayStockRTInfoByStockId(String stockId){
        if(String.isBlank(stockId)) return null;
        return getTodayStockRTInfoByStockIds(new String[]{stockId});
    }


}