StockMarket/src/objects/Stock__c.object
<CustomObject>
    <description>股票信息</description>
    <fields>
        <fullName>Stock_Code__c</fullName>
        <description>股票编码</description>
        <label>Stock Code</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Stock_Exchange__c</fullName>
        <description>交易所代码</description>
        <label>Stock Exchange</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>sh</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>sz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_Full_Name__c</fullName>
        <formula>TEXT(Stock_Exchange__c) &amp;   Stock_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stock Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Market_Index__c</fullName>
        <defaultValue>false</defaultValue>
        <description>是否股指，默认为否</description>
        <label>Stock Market Index</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isGrab__c</fullName>
        <defaultValue>true</defaultValue>
        <description>是否抓取</description>
        <label>isGrab</label>
        <type>Checkbox</type>
    </fields>
    <label>Stock</label>
    <nameField>
        <label>股票名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

StockMarket/src/classes/MyStockDao.cls
/**
 * 重构示例，外观
 */
public without sharing class MyStockDao extends BaseDao {
    
    private StockDao sDao;
    
    public MyStockDao(){
    	this.sDao = new StockDao();
    	this.sosql_all = 'SELECT Id,Name,isGrab__c,Stock_Code__c,Stock_Exchange__c,Stock_Full_Name__c,'
			+'Stock_Market_Index__c FROM Stock__c ';
    }

	public List<Stock__c> getAllStockList(){
		return sDao.getAllStockList();
	}

	public List<Stock__c> getStockListByIds(String[] Ids){
		return sDao.getStockListByIds(Ids);
	}

	public Stock__c getStockById(String stockId){
		return sDao.getStockById(stockId);
	}

	public List<Stock__c> getStockByCondition(String condition){
		return sDao.getStockByCondition(condition);
	}

	public List<Stock__c> getStockListByNames(String[] names){
		return sDao.getStockListByNames(names);
	}
	
	public Stock__c getStockByName(String stockName){
		return sDao.getStockByName(stockName);
	}

	public List<Stock__c> getStockListByCodes(String[] codes){
		return sDao.getStockListByCodes(codes);
	}

	public Stock__c getStockByCode(String code){
		return sDao.getStockByCode(code);
	}

	/**
	 [removeByCodes 传入股票代码数组，删除对应股票]
	 * @param  codes [description]
	 * @return       [description]
	 */
	public List<String> removeByCodes(String [] codes){
		if(null == codes) return null;
		if(codes.isEmpty()) return null;
		return remove(this.getStockListByCodes(codes));
	}

	/**
	 [removeByCode 删除对应code的股票]
	 * @param  code [description]
	 * @return      [description]
	 */
	public List<String> removeByCode(String code){
		if(String.isBlank(code)) return null;
		return removeByCodes(new String[]{code});
	}

}